# Generated by Django 5.1 on 2024-09-23 14:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('author', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(verbose_name='date published')),
                ('summarized_content', models.TextField()),
                ('original_image', models.ImageField(upload_to='media/blog/%Y/%m/%d')),
                ('resized_image', models.ImageField(editable=False, upload_to='media/blog/%Y/%m/%d')),
                ('thumbnail_image', models.ImageField(editable=False, upload_to='media/blog/%Y/%m/%d')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory')),
            ],
        ),
    ]
