# Generated by Django 5.1 on 2024-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('datetime_posted', models.DateTimeField(verbose_name='date published')),
                ('camera_model', models.CharField(max_length=50)),
                ('lens_model', models.CharField(max_length=50)),
                ('focal_length', models.IntegerField()),
                ('iso', models.IntegerField(default=200)),
                ('aperture', models.FloatField()),
                ('exposure_time', models.FloatField()),
                ('original_image', models.ImageField(upload_to='media/photo_gallery/%Y/%m/%d')),
                ('resized_image', models.ImageField(editable=False, upload_to='media/photo_gallery/%Y/%m/%d')),
                ('thumbnail_image', models.ImageField(editable=False, upload_to='media/photo_gallery/%Y/%m/%d')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='photo_gallery.phototag')),
            ],
        ),
    ]
