name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 536331667549.dkr.ecr.eu-central-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1

    - name: Build the Docker image
      run: docker build -t django_app .

    - name: Tag the Docker image
      run: docker tag django_app:latest 536331667549.dkr.ecr.eu-central-1.amazonaws.com/django_app:latest

    - name: Push the Docker image to ECR
      run: docker push 536331667549.dkr.ecr.eu-central-1.amazonaws.com/django_app:latest

    - name: Register Task Definition
      run: |
        aws ecs register-task-definition --cli-input-json file://./configs/infra/ecs-task-definition.json --debug
        

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster django_app_c \
          --service django-app6 \
          --task-definition django-app-ecs-task:latest \
          --force-new-deployment

    - name: Stop Previous Task
      run: |
        old_task=$(aws ecs list-tasks --cluster django_app_c --service-name django-app6 --query 'taskArns[0]' --output text)
        aws ecs stop-task --cluster django_app_c --task $old_task
