name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - feature/ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 536331667549.dkr.ecr.eu-central-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build the Docker image
      run: docker build -t django_app .

    - name: Tag the Docker image
      run: docker tag django_app:latest 536331667549.dkr.ecr.eu-central-1.amazonaws.com/django_app:latest

    - name: Push the Docker image to ECR
      run: docker push 536331667549.dkr.ecr.eu-central-1.amazonaws.com/django_app:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster django_app_c --service django-app6 --force-new-deployment